### PR TITLE
Add logic to draw borders on CanvasRenderer

### PR DESCRIPTION
**Pull request by jieyanhuang**
Paired with @yangbin 

@tgohn @zz85

### CODE REVIEW

**Comment by zz85** [comment]
looks good to me :+1:

**Comment by yangbin** [comment]
Maybe it should be another PR, but we should port over the `'blah' in attr` checks from HTMLRenderer. :+1: either way

**Comment by tgohn** [comment]
:+1:

**Comment by jieyanhuang** [comment]
@yangbin, let's clean that up in a separate PR

**Pull request merged**
